networks:
  myFood-network:

services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStrong_Password123#
    networks:
      - myFood-network

  WebApi:
    container_name: WebApiContainer
    image: ${DOCKER_REGISTRY-}my-food-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8080 
    environment:
      # Changed : to __ for better compatibility
      - ConnectionStrings__DefaultConnection=Data Source=SqlServerDb;Initial Catalog=MyFood_Database;User Id=sa;Password=MyStrong_Password123#;Connect Timeout=30;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - SqlServerDb
    networks:
      - myFood-network