name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '10.0.x'
    - name: Restore dependencies
      run: dotnet restore MyFood.sln
    - name: Build with dotnet
      run: dotnet build MyFood.sln --configuration Release --no-restore
